version: '2'
services:
  db:
    image: mongo:3.0.15
    environment:
      - MAX_CONNECTIONS=200
    ports:
      - 27017:27017
    volumes:
      - './docker/mongodb/data:/var/lib/mongodb'
      - './docker/mongodb/conf.d:/etc/mongodb/conf.d'
